### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cmoore-sp** [yallie/as_zip#3]
Hey, thanks for maintaining this ZIP utility. Deeply appreciated.

is there any documentation or sample code for running/calling this? It seems that the emphasis is zipping files from a folder local to the server. I need to zip files as blobs that I'll pull from AWS S3.

**Comment by dstrack** [comment]
Hi Christina, have a look at my project where i use this library to unzip blobs from a table.
https://github.com/dstrack/strack-software-unzip-parallel-plugin
The procedure Expand_Zip_Range in file unzip_parallel.sql may give you some hints.

Regards 
Dirk

**Comment by dstrack** [comment]
This library is almost identical to apex_zip. So have a look at this documentation:
https://docs.oracle.com/cd/E59726_01/doc.50/e39149/apex_zip.htm#AEAPI29942
